name: Deploy

# Trigger this workflow on a push to the main branch
on:
  push:
    branches:
      - main

# Define the deployment job
jobs:
  deploy:
    # The runner used for the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Deploy changes (e.g., commit & push)
      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Personal Access Token stored in GitHub Secrets
        run: |
          # Make sure the working directory is clean
          git add -A
          git commit -m "Automated deployment via GitHub Actions" || echo "No changes to commit"
          git push https://${{ secrets.GH_PAT }}@github.com/pranav0040/To-Do-List.git main
